### ISSUE TITLE
Test 24 emulated strips as will be expected in production

### ISSUE THREAD

**Issue by karlmutch** [TeamNorCal/mawt#11]
As a user of the mawt server
I want to have a universe of three fadecandy devices with all strips populated defined and tested
In order that the production setup can be validated via the color debugging display prior to hardware being fully available

Emulate the production setup without hardware using the LED strip display that is built into mawt, with a slow display refresh, or a TUI added with high display rate while leaving the internal refresh rate at the production rate.

Measure the blocking and concurrency using a Pi 3 along with using the Linux version for validation and profiling.

**Comment by scottmc** [comment]
Plan is to use 2 fade candy, with 8 strips of 60 LEDs (2 windows worth) on the tower and 4 strips of 60 LEDs on the base.

![pharos-cables](https://user-images.githubusercontent.com/1039279/39605477-7aca146a-4ee5-11e8-9e5e-82876d008fa2.png)
